export const listingsData = {
    listings: [
        {
            title: "Abbey Road (2012 Remaster)",
            artist: "The Beatles",
            price: 89.99,
            condition: "Near Mint (NM)",
            genre: "Rock",
            releaseYear: 2012,
            format: "LP, Album, Remastered",
            description:
                "2012 remastered pressing of The Beatles' iconic album 'Abbey Road'. This copy is in excellent condition, pressed on 180g vinyl for superior sound quality. The updated packaging includes restored artwork and liner notes. A great way to experience this classic album with modern audio fidelity.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678968/mock-album-covers/vmnjsz7ozj3jwpjpihxg.jpg",
                "/placeholder.svg?height=500&width=500&text=Abbey+Road+Vinyl",
                "/placeholder.svg?height=500&width=500&text=Gatefold+Interior",
                "/placeholder.svg?height=500&width=500&text=Label+Close-up",
            ],
            seller: {
                name: "VintageVinylVault",
                avatar: "/placeholder.svg?height=100&width=100&text=VVV",
                rating: 4.8,
                reviews: 1243,
            },
        },
        {
            title: "Bad - First US Pressing",
            artist: "Michael Jackson",
            price: 149.99,
            condition: "Very Good Plus (VG+)",
            genre: "Pop",
            releaseYear: 1987,
            format: "LP, Album",
            description:
                "First US pressing of Michael Jackson's legendary album 'Bad'. This copy is in very good plus condition, showing light signs of play but maintaining excellent sound quality. The cover has minor wear on the edges. Includes the original inner sleeve with lyrics.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678971/mock-album-covers/b7dyh9xheynzpy3zfl5s.webp",
                "/placeholder.svg?height=500&width=500&text=Bad+Vinyl",
                "/placeholder.svg?height=500&width=500&text=Inner+Sleeve",
                "/placeholder.svg?height=500&width=500&text=Back+Cover",
            ],
            seller: {
                name: "KingOfPopCollectibles",
                avatar: "/placeholder.svg?height=100&width=100&text=KPC",
                rating: 4.9,
                reviews: 876,
            },
        },
        {
            title: "Enter the Wu-Tang (36 Chambers) [25th Anniversary]",
            artist: "Wu-Tang Clan",
            price: 79.99,
            condition: "Mint (M)",
            genre: "Hip Hop",
            releaseYear: 2018,
            format: "2xLP, Album, Reissue, Special Edition",
            description:
                "25th Anniversary Edition of Wu-Tang Clan's groundbreaking debut 'Enter the Wu-Tang (36 Chambers)'. This special reissue is pressed on yellow vinyl and includes a booklet with rare photos and new liner notes. A fantastic way to celebrate this hip hop masterpiece.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678968/mock-album-covers/mdcufqjtmtnvxmxfkqaw.webp",
                "/placeholder.svg?height=500&width=500&text=36+Chambers+Yellow+Vinyl",
                "/placeholder.svg?height=500&width=500&text=Anniversary+Booklet",
                "/placeholder.svg?height=500&width=500&text=Gatefold+Artwork",
            ],
            seller: {
                name: "EastCoastBeats",
                avatar: "/placeholder.svg?height=100&width=100&text=ECB",
                rating: 4.7,
                reviews: 592,
            },
        },
        {
            title: "Kind of Blue (1970s Columbia Reissue)",
            artist: "Miles Davis",
            price: 299.99,
            condition: "Excellent (EX)",
            genre: "Jazz",
            releaseYear: 1959,
            format: "LP, Album, Reissue",
            description:
                "1970s Columbia reissue of Miles Davis' seminal album 'Kind of Blue'. This copy is in excellent condition, offering a more affordable way to own this jazz masterpiece on vinyl. The sound quality is superb, and the cover is well-preserved with minimal wear.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678968/mock-album-covers/kmfi56bvwdeptoajjrkr.jpg",
                "/placeholder.svg?height=500&width=500&text=Kind+of+Blue+Vinyl",
                "/placeholder.svg?height=500&width=500&text=Columbia+Label",
                "/placeholder.svg?height=500&width=500&text=Cover+Back",
            ],
            seller: {
                name: "JazzTreasures",
                avatar: "/placeholder.svg?height=100&width=100&text=JT",
                rating: 5.0,
                reviews: 201,
            },
        },
        {
            title: "Led Zeppelin I - 50th Anniversary Deluxe",
            artist: "Led Zeppelin",
            price: 129.99,
            condition: "Near Mint (NM)",
            genre: "Rock",
            releaseYear: 2018,
            format: "3xLP, Album, Remastered, Deluxe Edition",
            description:
                "50th Anniversary Deluxe Edition of Led Zeppelin's self-titled debut album. This set includes the remastered album plus a LP of studio outtakes and live recordings. Pressed on 180g vinyl with replica artwork and a hardbound book. A must-have for Led Zeppelin fans.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678968/mock-album-covers/jo8vfxgvaqtdpkzg20sf.webp",
                "/placeholder.svg?height=500&width=500&text=Led+Zeppelin+Vinyl+Set",
                "/placeholder.svg?height=500&width=500&text=Hardbound+Book",
                "/placeholder.svg?height=500&width=500&text=Outtakes+LP",
            ],
            seller: {
                name: "RockLegends",
                avatar: "/placeholder.svg?height=100&width=500&text=RL",
                rating: 4.8,
                reviews: 1567,
            },
        },
        {
            title: "Master of Puppets (1986 Elektra)",
            artist: "Metallica",
            price: 399.99,
            condition: "Very Good Plus (VG+)",
            genre: "Metal",
            releaseYear: 1986,
            format: "LP, Album",
            description:
                "Original 1986 Elektra pressing of Metallica's landmark album 'Master of Puppets'. This copy is in very good plus condition, showing some signs of play but maintaining excellent sound quality. The cover has light wear on the edges and corners. A true piece of metal history.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678968/mock-album-covers/qkergsnnykjukxlmm7vb.webp",
                "/placeholder.svg?height=500&width=500&text=Master+of+Puppets+Vinyl",
                "/placeholder.svg?height=500&width=500&text=Inner+Sleeve",
                "/placeholder.svg?height=500&width=500&text=Elektra+Label",
            ],
            seller: {
                name: "MetalVinylMania",
                avatar: "/placeholder.svg?height=100&width=100&text=MVM",
                rating: 4.9,
                reviews: 742,
            },
        },
        {
            title: "Nevermind - 20th Anniversary Remaster",
            artist: "Nirvana",
            price: 89.99,
            condition: "Near Mint (NM)",
            genre: "Rock",
            releaseYear: 2011,
            format: "2xLP, Album, Remastered, 20th Anniversary Edition",
            description:
                "20th Anniversary Edition of Nirvana's groundbreaking album 'Nevermind'. This remastered version is pressed on 180g vinyl and includes a bonus LP of rarities and B-sides. The iconic cover art is reproduced with high-quality printing. A great way to experience this 90s classic.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678971/mock-album-covers/k9cf8y5om9vwafdjkk20.jpg",
                "/placeholder.svg?height=500&width=500&text=Nevermind+Vinyl+Set",
                "/placeholder.svg?height=500&width=500&text=Bonus+LP",
                "/placeholder.svg?height=500&width=500&text=Anniversary+Insert",
            ],
            seller: {
                name: "GrungeGems",
                avatar: "/placeholder.svg?height=100&width=100&text=GG",
                rating: 4.7,
                reviews: 913,
            },
        },
        {
            title: "Paranoid - Original 1970 UK Vertigo",
            artist: "Black Sabbath",
            price: 799.99,
            condition: "Very Good (VG)",
            genre: "Metal",
            releaseYear: 1970,
            format: "LP, Album",
            description:
                "Original 1970 UK pressing of Black Sabbath's iconic album 'Paranoid'. This copy is in very good condition, playing with some surface noise but no skips. The cover shows wear but remains fully intact. Features the original Vertigo 'swirl' label. A rare opportunity to own a piece of heavy metal history.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678970/mock-album-covers/gus6hztsuyvrlw57zzpn.jpg",
                "/placeholder.svg?height=500&width=500&text=Paranoid+Vinyl",
                "/placeholder.svg?height=500&width=500&text=Vertigo+Swirl+Label",
                "/placeholder.svg?height=500&width=500&text=Back+Cover",
            ],
            seller: {
                name: "HeavyVinylHaven",
                avatar: "/placeholder.svg?height=100&width=100&text=HVH",
                rating: 4.8,
                reviews: 651,
            },
        },
        {
            title: "Rumours [2009 Remastered 180g]",
            artist: "Fleetwood Mac",
            price: 39.99,
            condition: "Near Mint (NM)",
            genre: "Rock",
            releaseYear: 2009,
            format: "LP, Album, Remastered",
            description:
                "2009 remastered pressing of Fleetwood Mac's classic album 'Rumours'. This version offers improved sound quality while maintaining the warmth of vinyl. Pressed on 180g vinyl with meticulously reproduced artwork. A fantastic way to experience this timeless album.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678969/mock-album-covers/nuhmfmnioj238h3yue0a.jpg",
                "/placeholder.svg?height=500&width=500&text=Rumours+Vinyl",
                "/placeholder.svg?height=500&width=500&text=Remastered+Label",
                "/placeholder.svg?height=500&width=500&text=Inner+Sleeve",
            ],
            seller: {
                name: "ClassicRockVinyl",
                avatar: "/placeholder.svg?height=100&width=100&text=CRV",
                rating: 4.9,
                reviews: 1876,
            },
        },
        {
            title: "The Fragile (Original 1999 3LP Set)",
            artist: "Nine Inch Nails",
            price: 299.99,
            condition: "Near Mint (NM)",
            genre: "Industrial Rock",
            releaseYear: 1999,
            format: "3xLP, Album",
            description:
                "First pressing of Nine Inch Nails' ambitious double album 'The Fragile'. This 3-LP set is in near mint condition, showing minimal signs of play. The triple gatefold cover is well-preserved with sharp corners. All original inserts are included. A fantastic copy of this late 90s industrial rock masterpiece.",
            images: [
                "https://res.cloudinary.com/oceansf/image/upload/v1728678971/mock-album-covers/g6jpitwb13jmfisblgnt.png",
                "/placeholder.svg?height=500&width=500&text=The+Fragile+Vinyl+Set",
                "/placeholder.svg?height=500&width=500&text=Gatefold+Interior",
                "/placeholder.svg?height=500&width=500&text=Nothing+Records+Label",
            ],
            seller: {
                name: "IndustrialVinylOutlet",
                avatar: "/placeholder.svg?height=100&width=100&text=IVO",
                rating: 4.7,
                reviews: 529,
            },
        },
    ],
};
