export default [
    { value: "12-lp", label: '12" LP' },
    { value: "7-single", label: '7" Single' },
    { value: "10-lp", label: '10" LP' },
    { value: "12-single", label: '12" Single' },
    { value: "12-ep", label: '12" EP' },
    { value: "7-ep", label: '7" EP' },
    { value: "78-rpm", label: "78 RPM" },
    { value: "picture-disc", label: "Picture Disc" },
    { value: "vinyl-box-set", label: "Box Set (Vinyl)" },
    { value: "cd-album", label: "CD Album" },
    { value: "cd-single", label: "CD Single" },
    { value: "cd-ep", label: "CD EP" },
    { value: "sacd", label: "SACD" },
    { value: "cd-box-set", label: "Box Set (CD)" },
    { value: "cassette", label: "Cassette" },
    { value: "cassette-single", label: "Cassette Single" },
    { value: "dat", label: "DAT" },
    { value: "cassette-box-set", label: "Box Set (Cassette)" },
    { value: "8-track", label: "8-Track" },
    { value: "minidisc", label: "Minidisc" },
    { value: "reel-to-reel", label: "Reel-to-Reel" },
    { value: "dvd-audio", label: "DVD Audio" },
    { value: "blu-ray-audio", label: "Blu-ray Audio" },
];